### ISSUE TITLE
Could not pass event ProjectileHitEvent to Sentries

### ISSUE THREAD

**Issue by MrZybez** [Jabelpeeps/Sentries#7]
[15:37:49] [Server thread/ERROR]: Could not pass event ProjectileHitEvent to Sentries v2.1.1(build-b159)
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-d5e7885]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-d5e7885]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-7d78b81-d5e7885]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-7d78b81-d5e7885]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:790) [spigot-1.11.2.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.EntityProjectile.A_(EntityProjectile.java:170) [spigot-1.11.2.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1629) [spigot-1.11.2.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.World.h(World.java:1604) [spigot-1.11.2.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1430) [spigot-1.11.2.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:617) [spigot-1.11.2.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:806) [spigot-1.11.2.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-7d78b81-d5e7885]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_11_R1.projectiles.CraftBlockProjectileSource cannot be cast to org.bukkit.entity.Entity
	at org.jabelpeeps.sentries.SentryListener.projectilehit(SentryListener.java:133) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-d5e7885]
	... 14 more

**Comment by Jabelpeeps** [comment]
Thx.  Usually a bit more information is helpful, however in this case I think I've fixed it in dev build [#163](https://jabelpeeps.org/jenkins/job/Sentries/163/) (on the jenkins server)

If you try it out, let me know how you get on.

**Comment by Jabelpeeps** [comment]
Did you get a chance to test this yet?

**Comment by Jabelpeeps** [comment]
I'm assuming this in now working for you, so I'm closing the issue.
